[project]
name = "cyclo"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "manim>=0.19.0",
    "pynput>=1.8.1",
    "python-vlc>=3.0.21203",
]
